---
title: "Gilchrist- Bootstrapping Motif Mean and Variance"
author: "Tara Empson"
date: "`r Sys.Date()`"
output: html_document
---

# Goal

# Background

# Libraries

```{r}
library(tidyverse)
library(modelr)
library(infer)
library(mosaic)
library(janitor)
library(boot)
```

# Local Functions

```{r}

# Function won't work if you use function(..., raw.data = raw.data)
# Why? R doesn't know which raw.data you mean (local or global)
# This is why you sometimes see .data as an argument name

bootstrapMeanAndVarOfColumn<- function(male, sample = 1000, col.name = "motif_count", data.raw = raw.data) {

  my_means <- vector(mode="double", length = sample)
  my_vars <- my_means

  data <- data.raw %>%
    filter(male %in% male) %>% 
    select(male, all_of(col.name)) # tidy warning told me to use 'all_of()' around col.name
  for(i in 1:sample){
    bootstrap_sample <- sample(raw.data$motif_count,n, replace = TRUE)
    my_means[i] <- mean(bootstrap_sample)
    my_vars[i] <- var(my_means)   
  }
  results <- tibble(male = male.focal, mean =  my_means, var = my_vars)
  return(results)
}

```
# Bootstraping data

## Load Data & Define Parameters

```{r}
setwd("../../data/collated/")
set.seed(1)
raw.data <- read.csv("HSPi-Repeatability-Song-Count.csv")
raw.data$day<- c(1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3)
#adding in day order

unique.male <- unique(raw.data$male)

n_sample <- 1000
n <- 3
#my_means <- 1:1000
#my_var <- 1:1000
```

## Bootstrap Data to Get Sample of Means and Vars for Each Male

```{r}



## Create tibble of mean and var from bootstrapped data
bs_stats  <- lapply(unique.male, bootstrapMeanAndVarOfColumn) %>%
  ## Combine bootstraped stats across males
  ## Note bind_rows will only work for a list, if you use sapply() you'll have a matrix of matricies
  bind_rows()

dim(bs_stats)

```


# Cruft

- This stuff didn't work and can be removed

Couldn't get a function to work so tried to make a for loop
```{r}
for (f in 1:length(unique.male)){
    raw.data %>%
    filter(male==f) %>%
    select(male, motif_count)
     for(i in 1:n_sample){
         bootstrap_sample <- sample(raw.data$motif_count,n, replace = TRUE)
         my_means[i] <- mean(bootstrap_sample)
         my_var[i] <- sqrt(sd(my_means))
         mean.of.means<- mean(my_means)
         var.of.means <- mean(my_var)
         
         result<- cbind.data.frame(f, mean.of.means,var.of.means)
         output <-rbind.data.frame(f, result)
         }
}

```


Couldn't get that to work either so white knuckling it
```{r}
unique.male
a <- "T247"
b <- "T236" 
c <- "T243"
d <- "T234"
e <- "T244" 
f <- "T231" 
g <- "T235"
h <- "T229"
j <- "T237"
k <- "T230"

n_sample <- 1000
n <- 3
my_means <- 1:1000
my_var <- 1:1000

{raw.data %>%
    filter(male==k) %>% 
    select(male, motif_count)
     for(i in 1:n_sample){
         bootstrap_sample <- sample(raw.data$motif_count,n, replace = TRUE)
         my_means[i] <- mean(bootstrap_sample)
         my_var[i] <- sqrt(sd(my_means))
         mean.of.means<- mean(my_means)
         var.of.means <- mean(my_var)
         result<- cbind.data.frame(mean.of.means,var.of.means)
         k.m.v <- result}}
id <- c("T247", "T236" ,"T243", "T234","T244" ,"T231" ,"T235","T229","T237","T230")
dataset=as.data.frame(rbind(a.m.v, b.m.v, c.m.v, d.m.v, e.m.v, f.m.v, g.m.v, h.m.v, j.m.v, h.m.v))
new.data<- cbind(id,dataset)
```


```{r}
new.data %>% 
    ggplot(aes(x=mean.of.means, y=var.of.means))+
     geom_point()+
    geom_smooth(method = "lm", formula = y ~ x)+
    geom_smooth(method = "lm", formula = y ~ x + I(x^2), color="red")+
    labs(x="Mean of Mean Number of Motifs", y="Variance of Mean Number of Motifs", caption = "Red line is quadradic and Blue is linear.", title="Bootstraping 1000 replications for each bird")+
    theme_classic()
```

