---
title: "Get Temperature"
author: "Tara Empson"
date: "`r Sys.Date()`"
output: html_document
---

#
```{r}
misc.info <- read.csv("MDSHrna_male_summary2023.11.14.csv") %>% 
    clean_names()
```

# Try to extract from data loggers but the file names don't match notes
```{r eval=FALSE, include=FALSE}
time.for.temp<- misc.info %>% 
    select(1:6) %>% 
    separate(date_euth, into = c("Month", "Day", "Year"), sep = "/") %>% 
    mutate(Month= sprintf("%02d", as.numeric(Month)),
           Day= sprintf("%02d", as.numeric(Day)),
           Year= str_c("20",Year)) %>% 
    mutate(euth_date=str_c(Month, "/", Day, "/", Year),
           final_real_trial_time_chamber_on=str_remove_all(final_real_trial_time_chamber_on," AM")) %>% 
    separate(final_real_trial_time_chamber_on, into = c("Hour", "Min"), sep = ":") %>% 
    mutate(Hour= sprintf("%02d",as.numeric(Hour)),
           Min=sprintf("%02d", as.numeric(Min)),
           final_real_trial_time_chamber_on=str_c(Hour,":",Min, ":00"),
           final_real_trial_time_door_opened=str_c(final_real_trial_time_door_opened, ":00")) %>% 
    select(-Hour, -Min, -Month, -Day, -Year)
```


```{r}
birds<- unique(time.for.temp$bird_id)
```

# Function to get average temp from chamber logger.
- Con of this is that it is only from while the camera was recording.
```{r}
gettemp<- function(i, birds){
    a.bird<- time.for.temp %>%
        filter(bird_id==i)
    
    a.chamber<- a.bird %>% pull(final_real_chamber_numb)
    
    path<- paste("../ch",a.chamber, sep="")
    setwd(path)
    
    find.file.name <- a.bird %>% separate(euth_date, into = c("Month", "Day", "Year"), sep = "/") %>% mutate(chamber.log.file=str_c("temp_log_",Year ,Month, Day, ".csv"))
    
    turn_chamber_on_time <- find.file.name %>% pull("final_real_trial_time_chamber_on")
    remove_bird_from_chamber_time <- find.file.name %>% pull("final_real_trial_time_door_opened")
    
    working<- read.csv(find.file.name$chamber.log.file, header=FALSE) %>% 
        separate(V1, into=c("Date","Time"), sep=" ") %>% 
        filter(Time>turn_chamber_on_time &
                   Time<remove_bird_from_chamber_time) #filtering to be only times when the chamber is on and a bird is in it. Just incase camera was running too long.
    
    a.bird$mean_temp <- mean(working$V4)
    a.bird
}
```

# Run function
```{r}
fin<- bind_rows(lapply(birds,gettemp))
```


```{r}
misc.info <- misc.info %>% 
    select(-final_real_trial_time_chamber_on)
fin <- fin %>% select(bird_id,final_real_trial_time_chamber_on, mean_temp)
done<- right_join(fin, misc.info, by=join_by(bird_id))
```


```{r}

#write_csv(done, "misc.data.w.temp.csv")
```

